name: php CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1  # Correct input name for region

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry: 688567291323.dkr.ecr.ap-northeast-1.amazonaws.com  # ECR registry to log in to

      - name: Build php Docker image
        run: |
          docker build -t php-ecr-server .
          docker tag php-ecr-server:latest 688567291323.dkr.ecr.ap-northeast-1.amazonaws.com/php-ecr-server:latest

      - name: Push php Docker image to ECR
        run: |
          docker push 688567291323.dkr.ecr.ap-northeast-1.amazonaws.com/php-ecr-server:latest
      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster php-cluster \
            --service php-mysql-service1 \
            --force-new-deployment
